version: 2

project_name: autent

builds:
  - id: autent-example
    main: ./cmd/autent-example
    binary: autent-example
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    ids:
      - autent-example

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  use: github-native
